// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oofkawnofnkbpgphlkcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZmthd25vZm5rYnBncGhsa2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjkyNzMsImV4cCI6MjA3MTkwNTI3M30.ur9174FkwNioTkuJzeo1A-W9tnzH3J9T8MGdVgsuGt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});